name: PR build

# https://futurestud.io/tutorials/github-actions-run-on-pull-request

on: [pull_request]

jobs:
  build:
    # https://github.com/orgs/community/discussions/25253
    runs-on: windows-2019
    timeout-minutes: 15
    # container: mcr.microsoft.com/dotnet/sdk:7.0
    steps:
      - uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: | 
            6.0.x
            7.0.x

      - name: Install dependencies
        run: dotnet restore .

      - name: Build
        run: dotnet build --configuration Release --no-restore .
   
      - name: Test
        run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage ./ 

      # - name: Code Coverage Report
      #   uses: irongut/CodeCoverageSummary@v1.3.0
      #   with:
      #     filename: coverage/**/coverage.cobertura.xml
      #     badge: true
      #     fail_below_min: false
      #     format: markdown
      #     hide_branch_rate: false
      #     hide_complexity: true
      #     indicators: true
      #     output: both
      #     thresholds: '50 50'
          
      # - name: Add Coverage PR Comment
      #   uses: marocchino/sticky-pull-request-comment@v2
      #   if: github.event_name == 'pull_request'
      #   with:
      #     recreate: true
      #     path: code-coverage-results.md

      # Do a pack (we don't care about the version because we're just going to throw it away)
      # just to make sure the solution is packable. It's unfortunate to make it to a post PR 
      # build to find out that we can't pack.
      - name: Pack
        run: dotnet pack --configuration Release /p:Version=1.0.0 --output . ./